#!/bin/bash
set -e

echo "PULLING"
git -C .. pull

echo "BUILDING"
NAME=stepswap-frontend
docker build . -t $NAME
docker run --rm -it -v $PWD/..:/mnt -w /mnt --name $NAME $NAME bash -c "/mnt/node_modules/.bin/nuxt generate" 


echo "DEPLOYING"
rsync -a --delete ../.output/public/ /root/html/app/


echo "DONE"

