#!/bin/bash
set -e

echo "PULLING"
git -C /root/frontend pull

echo "BUILDING"
NAME=stepswap-frontend
docker build /root/frontend/docker -t stepswap-frontend
docker run --rm -it -v /root/frontend:/mnt -w /mnt --name stepswap-frontend stepswap-frontend bash -c "npm i && /mnt/node_modules/.bin/nuxt generate" 


echo "DEPLOYING"
rsync -a --delete /root/frontend/.output/public/ /root/html/app/


echo "DONE"

